# Model for PPO finetuning
model_name_or_path: ../data/sft
use_peft: true
lora_alpha: 16
lora_r: 8
lora_dropout: 0.1
output_dir: ../data/ppo/llama3-ppo

# Reward model
reward_model: http://localhost:8000
discount_reward_factor: 0.99

# Dataset
query_dataset: stair-lab/airbench-ppo
ppo_epochs: 1
mini_batch_size: 1
batch_size: 1

# Hyperparameters
gradient_accumulation_steps: 1
gradient_checkpointing: true
learning_rate: 1.0e-4
save_steps: 1

max_new_tokens: 256