# Model for PPO finetuning
model_name_or_path: ../data/sft/qwen_full_10epoch/checkpoint-1000
use_peft: false
# lora_alpha: 512
# lora_r: 256
# lora_dropout: 0.1
# lora_target_modules: ["q_proj", "v_proj"]
output_dir: ../data/ppo/qwen3b-ppo

# Reward model
reward_model: http://hyperturing2:4324

# Dataset
query_dataset: stair-lab/airbench-ppo-qwen
ppo_epochs: 4
mini_batch_size: 1
batch_size: 1

# Hyperparameters
gradient_accumulation_steps: 1
gradient_checkpointing: true
learning_rate: 1.0e-4
save_steps: 50

max_new_tokens: 1024
log_with: wandb